spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@192.168.43.176:1521:orcl
    username: xx
    password: 123

server:
  port: 80
  servlet:
    context-path: /wuliuxm

mybatis:
  type-aliases-package: com.hlp.model
  mapper-locations: classpath:com/hlp/model/*.xml
